---

- hosts: all
  become: true

  tasks:
    - name: Remove the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: absent

    - name: Remove the latest version of dOker
      ansible.builtin.yum:
        name: docker
        state: absent